word_list = ['Tiger',
            'Wolf',
            'Fish',
             ' Elephant ',
             'Turtle',
             'Panda',
             'Leopard',
             'Giraffe',
             'Raccoon',
             'Crocodile',
             'Cheetah',
             'Whale',
             'Butterfly',
             'Hyena',
             'Parrot',
             'Deer',
             'Horse']